"""change priotity to priority

Revision ID: 2f0a861c8afe
Revises: 69bc2b4d20bf
Create Date: 2026-03-18 13:34:17.035274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f0a861c8afe'
down_revision: Union[str, Sequence[str], None] = '69bc2b4d20bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('priority', sa.String(length=10), server_default='Средний', nullable=False))
    op.drop_column('tasks', 'priotity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('priotity', sa.VARCHAR(length=10), server_default=sa.text("'Средний'::character varying"), autoincrement=False, nullable=False))
    op.drop_column('tasks', 'priority')
    # ### end Alembic commands ###
