"""Additional columns to tables

Revision ID: 69bc2b4d20bf
Revises: 49a42dbfdd79
Create Date: 2026-03-18 13:15:55.519219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69bc2b4d20bf'
down_revision: Union[str, Sequence[str], None] = '49a42dbfdd79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('due_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('priotity', sa.String(length=10), server_default='Средний', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'priotity')
    op.drop_column('tasks', 'completed_at')
    op.drop_column('tasks', 'due_date')
    # ### end Alembic commands ###
